### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by moosefaceee** [react-native-tvos/IgniteTV#2]
Hi there, sorry for opening an issue I tried to find a discord to ask questions but couldn't. 

Might sound a bit dumb, I understand and can get the application up and running on an emulator on my Mac, but how would I test the app on the Android TV itself? 

Happy to close this issue and move conversation elsewhere if more appropriate.

Thanks a bunch!

**Comment by douglowder** [comment]
@moosefaceee you can ask questions in the [Expo discord](https://discord.com/invite/expo), in the #react-native-tv channel.

Google documents how to set up for Android TV development and connect to a real device in [this document](https://developer.android.com/training/tv/start/start#run-on-a-real-device). It is essentially the same process as that used for Android phones. Once you have a device connected, you can run this app with `yarn android --device <device name>`. For a standalone build that does not require a connection to your development server (packager), you can do `yarn android --variant release --device <device name>`.

**Comment by moosefaceee** [comment]
Cheers, thank you @douglowder! I'm on the Expo discord so that is perfect.
